version: '3.8'

services:
  ms-contenedores:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-contenedores
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mi_base
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      MS_TRANSPORTES_URL: http://host.docker.internal:8085
    ports:
      - "8080:8080"
    networks:
      - contenedorespostgres_default

networks:
  contenedorespostgres_default:
    external: true