version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: mi_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mi_base
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    external: true  # Usa el volumen que ya creaste