version: '3.8'

services:
  ms-transportes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-transportes
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mi_base
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8081:8081"
    networks:
      - contenedorespostgres_default

networks:
  contenedorespostgres_default:
    external: true